compile1:
	gcc Q1_part1.c -o ans1
# 	Compile your code for first part here

run1: compile1
	./ans1
# 	 Execute part 1 here

compile2:
	gcc -pthread Q1_part2.c -o ans2
# 	Compile your code for second part here

run2: compile2
	./ans2
#	Execute part 2 here
clean:
	rm ans*